### ISSUE TITLE
Start designing on site leads to broken link

### ISSUE THREAD

**Issue by tamielbr** [vanila-io/wireflow2#7]
I know this isn't the best place to post this, but couldn't find a contact information. When clicking on button START DESIGNING on the site https://wireflow.co/, leads to this error:

```
Page Not Found

Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

Back to our site
```

**Comment by entrptaher** [comment]
@tamielbr The issues has been fixed on #6
